"""change account_number to BIGINT

Revision ID: 0adb7e061967
Revises: 9ff60fd7acae
Create Date: 2026-02-19 19:39:02.050366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0adb7e061967'
down_revision: Union[str, None] = '9ff60fd7acae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.alter_column('users', 'account_number',
                    existing_type=sa.INTEGER(),
                    type_=sa.BIGINT(),
                    existing_nullable=False,
                    existing_unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
