"""Changed the string to integer

Revision ID: 10cb60f0cc1c
Revises: 05d43766574e
Create Date: 2026-02-18 23:41:45.871865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10cb60f0cc1c'
down_revision: Union[str, None] = '05d43766574e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
    "ALTER TABLE users ALTER COLUMN transaction_pin TYPE INTEGER USING transaction_pin::integer"
)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'transaction_pin',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
