"""added account number column

Revision ID: 26561b4d0e0c
Revises: 10cb60f0cc1c
Create Date: 2026-02-19 07:44:36.440427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26561b4d0e0c'
down_revision: Union[str, None] = '10cb60f0cc1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_number', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users', ['account_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'account_number')
    # ### end Alembic commands ###
