"""add nin and bvn columns to users table

Revision ID: 328a3fbbc83e
Revises: ec1d5636d296
Create Date: 2026-02-18 22:38:49.410379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '328a3fbbc83e'
down_revision: Union[str, None] = 'ec1d5636d296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nin', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bvn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bvn')
    op.drop_column('users', 'nin')
    # ### end Alembic commands ###
