"""Change account_number to BigInteger

Revision ID: 6d544d3e6f4d
Revises: b1a009a093cf
Create Date: 2026-02-19 09:35:49.231603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d544d3e6f4d'
down_revision: Union[str, None] = 'b1a009a093cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # In your upgrade() function
    op.alter_column('users', 'account_number',
                    existing_type=sa.Integer(),
                    type_=sa.BigInteger(),
                    existing_nullable=False,
                    existing_unique=True)
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
